stages:
- install
- build
- test
- deploy
variables:
  NODE_VERSION: latest
install:
  stage: install
  image: node:latest
  script:
  - yarn install
  artifacts:
    paths:
    - node_modules/
    expire_in: 1 hour
build:
  stage: build
  image: node:latest
  script:
  - yarn run build
  artifacts:
    paths:
    - dist/
    expire_in: 1 hour
  dependencies:
  - install
test:
  stage: test
  image: node:latest
  script:
  - yarn run test
  artifacts:
    when: always
    reports:
      junit: '**/test-results/*.xml'
  dependencies:
  - install
  - build
deploy:
  stage: deploy
  image: alpine:latest
  script:
  - echo 'Deploy step'
  only:
  - main
